before_script:
  - "ssh-keygen -N '' -C 'build-test' -f ~/.ssh/id_rsa"
  - "cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys"
language: ruby
cache: bundler
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
notifications:
  email: false
  irc:
    channels:
      - ircs://irc.oftc.net:6697#akerl
    channel_key: sekrit
    template:
      - '%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}'
